### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by shmsw25** [snuhci2017/PopulationSimulation#10]
population
- [ ] make tooltip? (about term)
- [x] meaning of pink and blue
- [x] color issue
- [ ] change the timeline after selecting an age

factor
- [x] put real data
- [x] end year to be 2040
- [x] Axis design
- [x] Factor Label
- [ ] Factor Axis Unit
- [ ] TimeLine Dragable as non snapping mode
- [ ] TimeLine animation when snapped into a year

navigation 
- [ ] make a description of the icon

**Comment by shmsw25** [comment]
for simulation formula: year | birthrate | factor 1 | factor 2 | factor 3 | factor 4
event: factor_changed { factor1 : { a : 3, b : 4}, factor2 : ....} => factor = a * year + b
